FROM ubuntu:14.04
MAINTAINER Monty Lennie <montylennie@gmail.com>
RUN apt-get update
RUN apt-get install -y nodejs npm
#COPY . /node
#RUN cd /opt/node/; npm install
EXPOSE 8080
#CMD ["nodejs", "/node/index.js"]